<?php

namespace AppBundle\Repository;

/**
 * BandRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BandRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $styleName
     * @return array
     */
    public function findByStyleName($styleName)
    {
        $query = $this->createQueryBuilder('b')
            ->select('b')
            ->leftJoin('b.style', 's')
            ->where('s.name = :style')
            ->setParameter('style', $styleName)
            ->orderBy('b.name', 'ASC');

        return $query->getQuery()->getResult();
    }
}
