<?php
/**
 * This class was automatically generated by GraphQL Schema generator.
 */
namespace AppBundle\GraphQL;

use AppBundle\GraphQL\Mutation\MutationType;
use Youshido\GraphQL\Schema\AbstractSchema;
use Youshido\GraphQL\Config\Schema\SchemaConfig;
use AppBundle\GraphQL\Query\QueryType;

class Schema extends AbstractSchema
{
    public function build(SchemaConfig $config)
    {
        $config
            ->setMutation(new MutationType())
            ->setQuery(new QueryType());
    }
}
